name: state_restoration_example
description: state_restoration_example
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  flutter_riverpod: ^2.1.3
  riverpod_annotation: ^1.2.1
  shared_preferences: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  build_runner: ^2.3.3
  riverpod_generator: ^1.2.0

flutter:
  uses-material-design: true
